version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-forum-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"

  app:
    image: forum
    container_name: forum-container
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - mysql
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - PORT=${PORT}

networks:
  mynetwork:
    driver: bridge

volumes:
  redis_data:
    driver: local