version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-forum-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  app:
    image: forum
    container_name: forum-container
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - mysql

networks:
  mynetwork:
    driver: bridge