server:
  port: '8080'

spring:
  application:
    name: alura-forum
  datasource:
    url: jdbc:mysql://localhost:3306/alura-forum-db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true


