server:
  port: '8080'
  servlet:
    context-path: /api/v1


spring:
  application:
    name: alura-forum
#  data:
#    rest:
#      basePath: /api
#      defaultMediaType: application/json
  datasource:
    url: jdbc:mysql://localhost:3306/alura-forum-db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true


