server:
  port: '8080'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alura-forum-db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  expiration: 60000
  secret: "9XwpRBnR+cOSsvyU9gzkgW24DtXe9JHb3NbK6NQ0uM+07v46qjgaHW+j65ZPhURViPdmIe87y"
